### ISSUE TITLE
/lac dbimport Legacy is not working [ LS 2.1.5, PaperSpigot 1.8.8-R0.1 ]

### ISSUE THREAD

**Issue by Ksehn** [lenis0012/LoginSecurity-2#101]
Hi @lenis0012 ,

I've tried to import my users.db from LoginSecurity 2.0.10 to the 2.1.5 version with the command _/lac dbimport Legacy_ but this only show an error message saying : _Couldn't perform import, please check log!_ 

The file users.db to "import" (and users.db.backup) is still in the LoginSecurity's folder. 

What I'm doing wrong ?

Thanks in advance !

**Comment by lenis0012** [comment]
were there any errors in the server.log?

**Comment by KsenMih** [comment]
Sorry, there are no errors. 

Here is the full latest.log when I've just tried to upgrade LoginSecurity without any command : https://hastebin.com/fuyamekiha.md . Despiste the "_Loading accounts from Legacy [0%]_" and "_All entries were loaded, now saving in to new database..._", and after the server stop :

- The file **users.db** is totally empty.
- The file **LoginSecurity.db** contains tables from LoginSecurity 2.1.5, but there are empty.
- The file **users.backup.db** contains tables and data from LoginSecurity 2.x.x.

I will try to achieve the migration directly on the production server. I don't know a lot of stuff about player's uuids, but, maybe the error is caused because I've tried the migration on a other "offline-mode" server.

**Comment by lenis0012** [comment]
@KsenMih Could you send me your old database file on spigotmc PM? (using google drive or dropbox)
The player passwords are stored in an encrypted format, so you're users security is not at risk.
If you don't wish to however, I will try to reproduce this on my own.

**Comment by KsenMih** [comment]
@lenis0012 No problems :) I will send you this in a few days (Currently not at home).

**Comment by lenis0012** [comment]
Closing this issue, please re-open if this is still an issue
